id: I78F77A2B
legacy_id: P000631
ocr_import_info:
  bdrc_scan_id: W1KG10663
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T12:38:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:48:03.863172+00:00'
last_modified: 2022-08-31 10:48:33.999729
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10663
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10663
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་བརྗོད་དང་དག་ཡིག་སོགས། ༼ཞོལ་པར་མ།༽
  author: ཞྭ་ལུ་ལོ་ཙཱ་བ་ཆོས་སྐྱོང་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.7638854518746043
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG10665:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10665
      total_pages: 354
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10665.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7638854518746043
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
