id: P000631
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:53:39.487164
source_metadata:
  id: bdr:W1KG10663
  title: མངོན་བརྗོད་དང་དག་ཡིག་སོགས། ༼ཞོལ་པར་མ།༽
  author: ''
  volumes:
    6bde345e33d94e3bb5e92ac8bf1db1e5:
      image_group_id: I1KG10665
      title: ''
      volume_number: 1
      total_pages: 354
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
